
package client_interface;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextArea;


public class Client_Interface extends javax.swing.JFrame {

    /**
     * Creates new form Client_Interface
     */
    
    static Client cliente;
     
    public Client_Interface(Client client) {
        initComponents();
        this.cliente=cliente;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pantalla = new javax.swing.JTextArea();
        Get1 = new javax.swing.JButton();
        Get2 = new javax.swing.JButton();
        Get3 = new javax.swing.JButton();
        Release1 = new javax.swing.JButton();
        Release2 = new javax.swing.JButton();
        Release3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Disconnect = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pantalla.setBackground(new java.awt.Color(204, 204, 255));
        pantalla.setColumns(20);
        pantalla.setRows(5);
        jScrollPane1.setViewportView(pantalla);

        Get1.setBackground(new java.awt.Color(153, 255, 255));
        Get1.setText("Get 1");
        Get1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Get1MouseClicked(evt);
            }
        });

        Get2.setBackground(new java.awt.Color(153, 255, 255));
        Get2.setText("Get 2");
        Get2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Get2MouseClicked(evt);
            }
        });
        Get2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Get2ActionPerformed(evt);
            }
        });

        Get3.setBackground(new java.awt.Color(153, 255, 255));
        Get3.setText("Get 3");
        Get3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Get3MouseClicked(evt);
            }
        });
        Get3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Get3ActionPerformed(evt);
            }
        });

        Release1.setBackground(new java.awt.Color(204, 0, 0));
        Release1.setText("Release 1");
        Release1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Release1MouseClicked(evt);
            }
        });

        Release2.setBackground(new java.awt.Color(255, 0, 0));
        Release2.setText("Release 2");
        Release2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Release2MouseClicked(evt);
            }
        });

        Release3.setBackground(new java.awt.Color(204, 0, 51));
        Release3.setText("Release 3");
        Release3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Release3MouseClicked(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Get resource 1");

        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Get resource 3");

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Get resource 2");

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Release resource 2");

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Release resource 3");

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Release resource 1");

        Disconnect.setBackground(new java.awt.Color(153, 153, 153));
        Disconnect.setText("Disconnect");
        Disconnect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DisconnectMouseClicked(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Disconnect");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(138, 138, 138)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Get1)
                                    .addComponent(Get2)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Get3)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(141, 141, 141)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Release3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Release1)
                                            .addComponent(Release2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Disconnect, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Get1)
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(Disconnect))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Release1)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Get2)
                            .addComponent(Release2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Get3)
                    .addComponent(Release3))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Get2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Get2ActionPerformed
      
    }//GEN-LAST:event_Get2ActionPerformed

    private void Get3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Get3ActionPerformed
    
    }//GEN-LAST:event_Get3ActionPerformed

    private void Get1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Get1MouseClicked
        
        cliente.down(1);
        
    }//GEN-LAST:event_Get1MouseClicked

    private void Get2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Get2MouseClicked
        
        cliente.down(2);
        
    }//GEN-LAST:event_Get2MouseClicked

    private void Get3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Get3MouseClicked
        
        cliente.down(3);
        
    }//GEN-LAST:event_Get3MouseClicked

    private void Release1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Release1MouseClicked
        
        cliente.up(1);
       
    }//GEN-LAST:event_Release1MouseClicked

    private void Release2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Release2MouseClicked
        
        cliente.up(2);
        
    }//GEN-LAST:event_Release2MouseClicked

    private void Release3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Release3MouseClicked
        
        cliente.up(3);
        
    }//GEN-LAST:event_Release3MouseClicked

    private void DisconnectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisconnectMouseClicked
        cliente.conexionCliente=false;
    }//GEN-LAST:event_DisconnectMouseClicked

    public JTextArea getPantalla() {
        return pantalla;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Disconnect;
    private javax.swing.JButton Get1;
    private javax.swing.JButton Get2;
    private javax.swing.JButton Get3;
    private javax.swing.JButton Release1;
    private javax.swing.JButton Release2;
    private javax.swing.JButton Release3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea pantalla;
    // End of variables declaration//GEN-END:variables
}
